# Generated by Django 5.0.1 on 2024-01-27 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_examinee_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='author',
        ),
    ]
