# Generated by Django 5.0.1 on 2024-02-07 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_answer_options_alter_choice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examinee',
            options={'verbose_name': 'شرکت کننده', 'verbose_name_plural': 'شرکت کنندگان'},
        ),
    ]
